# shell bash

background_opacity 0.96
background_blur 1

enable_audio_bell no

linux_display_server x11
font_family      family='JetBrainsMono Nerd Font Mono' postscript_name=JetBrainsMonoNFM-Regular
bold_font        family='JetBrainsMono Nerd Font Mono' postscript_name=JetBrainsMonoNFM-Medium
italic_font      family='JetBrainsMono Nerd Font Mono' postscript_name=JetBrainsMonoNFM-Italic
bold_italic_font family='JetBrainsMono Nerd Font Mono' postscript_name=JetBrainsMonoNFM-MediumItalic
font_size 16.0

confirm_os_window_close 0

clear_all_shortcuts yes

map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard
map ctrl+shift+plus change_font_size all +2.0
map ctrl+shift+equal change_font_size all +2.0
map ctrl+shift+minus change_font_size all -2.0

color4 #5fafff
color12 #87d7ff

underline_style wavy
