#!/bin/bash
# Copyright 2025 Dany Gagnon <dany@ovior.ca>
#
# Licensed under the terms of the GNU GPL v3, or any later version.

iface=$(nmcli -t -f DEVICE,STATE dev status | grep ":connected" | cut -d: -f1 | head -n 1)

if [ -z "$iface" -o "$iface" == "lo" ]; then
    echo "Disconnected"
    echo "Disconnected"
    echo \#FF0000
    exit 0
fi

ssid=$(nmcli -t -f active,ssid dev wifi | awk -F: '$1 == "yes" {print $2}')
ip=$(ip -4 addr show "$iface" | grep -oP '(?<=inet\s)\d+(\.\d+){3}')

vpn=$(nmcli -t -f NAME,TYPE con show --active \
  | grep -E ':(vpn|wireguard)$' \
  | cut -d: -f1 \
  | head -n1)

if [ -z "$ssid" ]; then
    output="Wired $ip"
else
    output="$ssid $ip"
fi

if [ -n "$vpn" ]; then
    output="$output (VPN: $vpn)"
fi

echo "$output"
echo "$output"
echo "#96cbfe"
